# Generated by Django 5.2.9 on 2025-12-09 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='CREATE', help_text="Main hero title (e.g., 'CREATE')", max_length=200)),
                ('hero_video', models.FileField(blank=True, help_text='Hero background video (.mp4, .webm)', null=True, upload_to='hero_videos/')),
                ('hero_text_static', models.CharField(default='Something', help_text="Static part of subtitle (e.g., 'Something')", max_length=100)),
                ('changing_text_words', models.TextField(default='ELEGANT,STUNNING,PREMIUM,CLASSIC', help_text="Comma-separated words for changing text animation (e.g., 'ELEGANT,STUNNING,PREMIUM,CLASSIC')")),
                ('description', models.TextField(blank=True, help_text='Hero description text (if needed)')),
                ('primary_cta_text', models.CharField(default='Start a Project', help_text='Primary CTA button text', max_length=50)),
                ('primary_cta_link', models.URLField(blank=True, default='/projects', help_text='Primary CTA button link')),
                ('secondary_cta_text', models.CharField(blank=True, help_text='Secondary CTA button text (optional)', max_length=50)),
                ('secondary_cta_link', models.URLField(blank=True, help_text='Secondary CTA button link (optional)')),
                ('show_blog_slider', models.BooleanField(default=True, help_text='Show blog/news slider in hero')),
                ('slider_title', models.CharField(blank=True, default='Latest News', help_text='Title for the blog/news slider', max_length=100)),
                ('hero_image', models.ForeignKey(blank=True, help_text='Hero background image (fallback if no video)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Main Hero Section',
                'verbose_name_plural': 'Main Hero Sections',
            },
        ),
    ]
