# Generated by Django 5.2.9 on 2025-12-09 07:15

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Latest Blog Posts', help_text='Slider title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle', max_length=300)),
                ('slides', wagtail.fields.StreamField([('blog_slide', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Brief description for the slide', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Slide image', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Internal Page', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Email (mailto:), phone (tel:), or hash (#section-id)', 'label': 'Custom Link', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('page_link', 3), ('external_link', 4), ('document_link', 5), ('free_link', 6)]], {'required': False}), 8: ('wagtail.blocks.DateBlock', (), {'help_text': 'Publication date (for news/blog slides)', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Category or tag', 'max_length': 100, 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Mark as featured slide', 'required': False}), 11: ('wagtail.blocks.TextBlock', (), {'help_text': 'Blog excerpt', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Comma-separated tags', 'max_length': 200, 'required': False}), 13: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Estimated reading time in minutes', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2), ('link', 7), ('date', 8), ('category', 9), ('featured', 10), ('excerpt', 11), ('tags', 12), ('read_time', 13)]], {})}, help_text='Add blog slides')),
                ('autoplay', models.BooleanField(default=True, help_text='Auto-play slides')),
                ('autoplay_delay', models.IntegerField(default=5000, help_text='Auto-play delay in milliseconds')),
                ('show_navigation', models.BooleanField(default=True, help_text='Show navigation arrows')),
                ('show_pagination', models.BooleanField(default=True, help_text='Show pagination dots')),
            ],
            options={
                'verbose_name': 'Blog Slider',
                'verbose_name_plural': 'Blog Sliders',
            },
        ),
        migrations.CreateModel(
            name='NewsSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Latest News', help_text='Slider title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle', max_length=300)),
                ('slides', wagtail.fields.StreamField([('news_slide', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Brief description for the slide', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Slide image', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Internal Page', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Email (mailto:), phone (tel:), or hash (#section-id)', 'label': 'Custom Link', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('page_link', 3), ('external_link', 4), ('document_link', 5), ('free_link', 6)]], {'required': False}), 8: ('wagtail.blocks.DateBlock', (), {'help_text': 'Publication date (for news/blog slides)', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Category or tag', 'max_length': 100, 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Mark as featured slide', 'required': False}), 11: ('wagtail.blocks.TextBlock', (), {'help_text': 'News excerpt', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'News author', 'max_length': 100, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2), ('link', 7), ('date', 8), ('category', 9), ('featured', 10), ('excerpt', 11), ('author', 12)]], {})}, help_text='Add news slides')),
                ('autoplay', models.BooleanField(default=True, help_text='Auto-play slides')),
                ('autoplay_delay', models.IntegerField(default=5000, help_text='Auto-play delay in milliseconds')),
                ('show_navigation', models.BooleanField(default=True, help_text='Show navigation arrows')),
                ('show_pagination', models.BooleanField(default=True, help_text='Show pagination dots')),
            ],
            options={
                'verbose_name': 'News Slider',
                'verbose_name_plural': 'News Sliders',
            },
        ),
        migrations.RemoveField(
            model_name='mainhero',
            name='show_blog_slider',
        ),
        migrations.RemoveField(
            model_name='mainhero',
            name='slider_title',
        ),
        migrations.AddField(
            model_name='mainhero',
            name='news_slider',
            field=models.ForeignKey(blank=True, help_text='Select news slider to display in hero (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.newsslider'),
        ),
    ]
