# Generated by Django 5.2.9 on 2025-12-09 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogslider_newsslider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainhero',
            name='blog_slider',
            field=models.ForeignKey(blank=True, help_text="Select blog slider (only used if slider type is 'Blog Slider')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.blogslider'),
        ),
        migrations.AddField(
            model_name='mainhero',
            name='slider_type',
            field=models.CharField(choices=[('none', 'No Slider'), ('news', 'News Slider'), ('blog', 'Blog Slider')], default='none', help_text='Choose which type of slider to display', max_length=20),
        ),
        migrations.AlterField(
            model_name='mainhero',
            name='news_slider',
            field=models.ForeignKey(blank=True, help_text="Select news slider (only used if slider type is 'News Slider')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.newsslider'),
        ),
    ]
