# Generated by Django 5.2.7 on 2025-12-09 08:58

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mainhero_blog_slider_mainhero_slider_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogslider',
            name='autoplay',
        ),
        migrations.RemoveField(
            model_name='blogslider',
            name='show_navigation',
        ),
        migrations.RemoveField(
            model_name='blogslider',
            name='show_pagination',
        ),
        migrations.RemoveField(
            model_name='blogslider',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='newsslider',
            name='autoplay',
        ),
        migrations.RemoveField(
            model_name='newsslider',
            name='show_navigation',
        ),
        migrations.RemoveField(
            model_name='newsslider',
            name='show_pagination',
        ),
        migrations.RemoveField(
            model_name='newsslider',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='blogslider',
            name='autoplay_delay',
            field=models.IntegerField(default=4200, help_text='Auto-play delay in milliseconds'),
        ),
        migrations.AlterField(
            model_name='blogslider',
            name='slides',
            field=wagtail.fields.StreamField([('blog_slide', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Internal Page', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Email (mailto:), phone (tel:), or hash (#section-id)', 'label': 'Custom Link', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('page_link', 1), ('external_link', 2), ('document_link', 3), ('free_link', 4)]], {'required': False}), 6: ('wagtail.blocks.DateBlock', (), {'help_text': 'Publication date (for news/blog slides)', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Category or tag', 'max_length': 100, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Mark as featured slide', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'Blog excerpt', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Comma-separated tags', 'max_length': 200, 'required': False}), 11: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Estimated reading time in minutes', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 0), ('link', 5), ('date', 6), ('category', 7), ('featured', 8), ('excerpt', 9), ('tags', 10), ('read_time', 11)]], {})}, help_text='Add blog slides'),
        ),
        migrations.AlterField(
            model_name='newsslider',
            name='autoplay_delay',
            field=models.IntegerField(default=4200, help_text='Auto-play delay in milliseconds'),
        ),
        migrations.AlterField(
            model_name='newsslider',
            name='slides',
            field=wagtail.fields.StreamField([('news_slide', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Internal Page', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Email (mailto:), phone (tel:), or hash (#section-id)', 'label': 'Custom Link', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('page_link', 1), ('external_link', 2), ('document_link', 3), ('free_link', 4)]], {'required': False}), 6: ('wagtail.blocks.DateBlock', (), {'help_text': 'Publication date (for news/blog slides)', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Category or tag', 'max_length': 100, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Mark as featured slide', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'News excerpt', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'News author', 'max_length': 100, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 0), ('link', 5), ('date', 6), ('category', 7), ('featured', 8), ('excerpt', 9), ('author', 10)]], {})}, help_text='Add news slides'),
        ),
    ]
