# Generated by Django 5.2.7 on 2025-12-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_blogslider_autoplay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainhero',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text='Hero video URL (alternative to uploaded video file)', null=True),
        ),
    ]
