# Generated by Django 5.2.9 on 2025-12-09 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_section',
            field=models.ForeignKey(blank=True, help_text='Select hero section for the homepage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mainhero'),
        ),
    ]
