# Generated by Django 5.2.7 on 2025-12-09 11:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_hero_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='essence_section',
            field=wagtail.fields.StreamField([('essence', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading for the essence section', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Description text for the essence section'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Call-to-action button text', 'max_length': 50}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Internal Page', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Email (mailto:), phone (tel:), or hash (#section-id)', 'label': 'Custom Link', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('page_link', 3), ('external_link', 4), ('document_link', 5), ('free_link', 6)]], {'help_text': 'Call-to-action button link'}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Main image for the essence section'}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('cta_text', 2), ('cta_link', 7), ('image', 8)]], {})}, help_text='Essence section content', null=True),
        ),
    ]
