# Generated by Django 5.2.7 on 2025-12-10 10:49

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(default='Payments', help_text='Main title for the payments page', max_length=255)),
                ('intro_text', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the payments page')),
                ('basic_form_enabled', models.BooleanField(default=True, help_text='Enable the basic information form')),
                ('basic_form_title', models.CharField(default='Basic Information Form', help_text='Title for the basic form', max_length=255)),
                ('basic_form_description', models.TextField(blank=True, help_text='Description for the basic form')),
                ('payment_form_enabled', models.BooleanField(default=True, help_text='Enable the payment form')),
                ('payment_form_title', models.CharField(default='Payment Form', help_text='Title for the payment form', max_length=255)),
                ('payment_form_description', models.TextField(blank=True, help_text='Description for the payment form')),
                ('step1_title', models.CharField(default='Personal Information', help_text='Title for payment form step 1', max_length=255)),
                ('step1_description', models.TextField(blank=True, help_text='Description for payment form step 1')),
                ('step2_title', models.CharField(default='Billing Address', help_text='Title for payment form step 2', max_length=255)),
                ('step2_description', models.TextField(blank=True, help_text='Description for payment form step 2')),
                ('step3_title', models.CharField(default='Payment Information', help_text='Title for payment form step 3', max_length=255)),
                ('step3_description', models.TextField(blank=True, help_text='Description for payment form step 3')),
                ('payment_processor', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('square', 'Square'), ('manual', 'Manual Processing')], default='manual', help_text='Choose payment processor', max_length=50)),
                ('publish_key', models.CharField(blank=True, help_text='Publishable key for payment processor', max_length=255)),
                ('success_message', models.TextField(default='Thank you for your payment! We will process your request shortly.', help_text='Message to show after successful payment')),
                ('error_message', models.TextField(default='There was an error processing your payment. Please try again.', help_text='Message to show if payment fails')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Featured image for the payments page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Payments Page',
                'verbose_name_plural': 'Payments Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
